#include <stdio.h>      // For input/output functions
#include <stdlib.h>     // For malloc and rand
#include <mpi.h>        // For MPI functions
#include <time.h>       // For seeding the random number generator

int main(int argc, char** argv) {
    int rank, size;             // Rank of the process and total number of processes
    int local_number;           // Random number generated by each process
    int *all_numbers = NULL;    // Array to store gathered numbers from all processes
    double max_value, avg_value; // To store max and average values
    double start_time, end_time; // For timing MPI operations
    int op_count = 1;           // Number of operations per process (for reporting)

    // Initialize MPI environment
    MPI_Init(&argc, &argv);

    // Get the rank (ID) of the process
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    // Get the total number of processes
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    // Seed the random number generator uniquely for each process
    srand(time(NULL) + rank);

    // Each process generates a random number between 1 and 100
    local_number = (rand() % 100) + 1;
    printf("Process %d: Generated number = %d\n", rank, local_number);

    // Allocate memory to hold the gathered numbers from all processes
    all_numbers = (int*)malloc(size * sizeof(int));

    // ---------- MPI_Allgather ----------
    // All processes share their local number with every other process
    start_time = MPI_Wtime();  // Start timing
    MPI_Allgather(&local_number, 1, MPI_INT, all_numbers, 1, MPI_INT, MPI_COMM_WORLD);
    end_time = MPI_Wtime();    // End timing

    // Print the time taken for MPI_Allgather and total operations
    printf("Process %d: MPI_Allgather time = %.6f seconds, operations = %d\n", 
           rank, end_time - start_time, op_count * size);

    // Only process 0 prints all gathered numbers
    if (rank == 0) {
        printf("Process 0: All gathered numbers: ");
        for (int i = 0; i < size; i++) {
            printf("%d ", all_numbers[i]);
        }
        printf("\n");
    }

    // ---------- MPI_Reduce ----------
    // Compute the maximum value across all processes and send the result to process 0
    start_time = MPI_Wtime();  // Start timing
    MPI_Reduce(&local_number, &max_value, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);
    end_time = MPI_Wtime();    // End timing

    // Only process 0 prints the maximum value and time taken
    if (rank == 0) {
        printf("Process 0: MPI_Reduce time = %.6f seconds, operations = %d, Max value = %.0f\n", 
               end_time - start_time, op_count, max_value);
    }

    // ---------- MPI_Allreduce ----------
    // Compute the sum of all local numbers and distribute the result to all processes
    start_time = MPI_Wtime();  // Start timing
    MPI_Allreduce(&local_number, &avg_value, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
    end_time = MPI_Wtime();    // End timing

    // Calculate average by dividing the sum by the number of processes
    avg_value /= size;

    // Each process prints the average value and time taken
    printf("Process %d: MPI_Allreduce time = %.6f seconds, operations = %d, Average value = %.2f\n", 
           rank, end_time - start_time, op_count, avg_value);

    // Free dynamically allocated memory
    free(all_numbers);

    // Finalize the MPI environment
    MPI_Finalize();
    return 0;
}
